title: Viktor Nilsson
author:
  name: Viktor Nilsson
  email: viktornilsson91@live.se

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
# description: >
#   Write an awesome description for your new site here. You can edit this line
#   in _config.yml. It will appear in your document head meta (for Google search
#   results) and in your feed.xml site description.

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Theme-specific settings
header_pages:
  - index.md
  - about.md

minima:
  skin: dark

# Generate social links in footer.
social_links:
  - { platform: github, user_url: "https://github.com/viktornilsson" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/viktor-nilsson-dotnet" }
