title: Viktor Nilsson
author:
  name: Viktor Nilsson
  email: viktornilsson91@live.se

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This blog is made to highlight things I work on as a Solution Architect at Eton Shirts.

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Theme-specific settings
header_pages:
  - index.md
  - about.md

minima:
  skin: dark
